### ISSUE TITLE
Systray icons are taking long space on the panel

### ISSUE THREAD

**Issue by sharif-jobayed** [linuxmint/linuxmint#459] opened 2022-01-15 13:27 UTC
I am using Linux Mint 20 Cinnamon. If I add many apps to the panel & system tray has also many apps in there then the app icons from both sides are joining each other & they are overlapping each other which is ugly & much confusing.
I think the systray icons visibility count should be limited & there should be a solution so that icons from both side do not mix up with each other but of course not making it so stupid like dropping off the entire systray system like elementary os! I know there may be some 3rd party addons or extensions to resolve it but the solution should be shipped as a default with the system. Linux Mint is my favorite OS, please fix this issue.
![2022-01-15_18-59](https://user-images.githubusercontent.com/49595427/149623356-b2f957db-075f-489c-b885-65d12d2c5069.png)
.

**Comment by fredcw** [comment] 2022-01-15 15:16
Duplicate of https://github.com/linuxmint/cinnamon/issues/5042

**Closed** 2022-01-15 19:06 UTC
