### ISSUE TITLE
Bug in Panel preference settings.

### ISSUE THREAD

**Issue by aerkiaga** [linuxmint/linuxmint#9] opened 2018-04-09 21:40 UTC
The sequence of actions that triggers it is the following: activate Panel edit mode, either from Preferences -> Panel, in which case go back to Preferences without deactivating it, or from the panel itself (with a Preferences window open and at least partially visible for the next step, I suppose). Now, still without deactivating, click on Panel, go back and repeat until a bunch of very small windows appear. If one is closed (might not work with all the windows that appear), the Panel settings window gets closed, but the Panel does not lose its red hue. Entering Panel and going back returns it to normal, but the problem may still be there, so entering and exiting Panel as before may re-trigger it.

After Panel is entered the first time with Panel edit mode activated, the bug is bound to be triggered even if it is deactivated afterwards. At this point, if Panel is entered again and exited a number of times (usually 1-3 in total), the small, black windows appear invariably.

When this happens, the parent window can apparently be closed normally. Doing this does return the panel to its normal color. When the normal color is returned, entering and exiting Panel repeatedly will not trigger the bug again. Sometimes, even if one black window has been closed and the panel has the red hue, entering Panel repeatedly will not trigger it.

This is a screenshot of the faulty panel, with the tabs that correspond to all the buggy open windows following the Panel tab:

![image](https://user-images.githubusercontent.com/38228836/38524218-2c46479a-3c4e-11e8-9f24-626820f89762.png)

System information, output of `inxi -Fxxrzc0`:
```
System:    Host: User-PC Kernel: 4.13.0-38-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.6.7 (Gtk 3.18.9-1ubuntu3.3) dm: lightdm
           Distro: Linux Mint 18.3 Sylvia
Machine:   System: ASUS product: All Series
           Mobo: ASUSTeK model: AM1M-A v: Rev X.0x
           Bios: American Megatrends v: 1302 date: 10/27/2015
CPU:       Quad core AMD Athlon 5350 APU with Radeon R3 (-MCP-) cache: 8192 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm) bmips: 16798
           clock speeds: min/max: 800/2000 MHz 1: 968 MHz 2: 1224 MHz
           3: 1263 MHz 4: 944 MHz
Graphics:  Card: NVIDIA GK208 [GeForce GT 730]
           bus-ID: 01:00.0 chip-ID: 10de:1287
           Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1366x768@59.79hz
           GLX Renderer: GeForce GT 730/PCIe/SSE2
           GLX Version: 4.5.0 NVIDIA 384.111 Direct Rendering: Yes
Audio:     Card-1 Advanced Micro Devices [AMD] FCH Azalia Controller
           driver: snd_hda_intel bus-ID: 00:14.2 chip-ID: 1022:780d
           Card-2 NVIDIA GK208 HDMI/DP Audio Controller
           driver: snd_hda_intel bus-ID: 01:00.1 chip-ID: 10de:0e0f
           Sound: Advanced Linux Sound Architecture v: k4.13.0-38-generic
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: d000
           bus-ID: 02:00.0 chip-ID: 10ec:8168
           IF: enp2s0 state: down mac: <filter>
           Card-2: Ralink RT5372 Wireless Adapter
           driver: rt2800usb v: 2.3.0 usb-ID: 002-002 chip-ID: 148f:5372
           IF: wlx9cefd5fd9e55 state: N/A mac: N/A
Drives:    HDD Total Size: 1240.3GB (2.8% used)
           ID-1: /dev/sda model: KINGSTON_SUV400S size: 240.1GB serial: 50026B7669014F30
           ID-2: /dev/sdb model: ST1000DM003 size: 1000.2GB serial: Z1D844CX
Partition: ID-1: / size: 198G used: 14G (8%) fs: ext4 dev: /dev/sda2
           ID-2: /home size: 557G used: 16G (3%) fs: ext4 dev: /dev/sdb4
           ID-3: swap-1 size: 4.09GB used: 0.00GB (0%) fs: swap dev: /dev/sda1
RAID:      System: supported: N/A
           No RAID devices: /proc/mdstat, md_mod kernel module present
           Unused Devices: none
Sensors:   System Temperatures: cpu: 12.2C mobo: N/A gpu: 0.0:35C
           Fan Speeds (in rpm): cpu: 0
Repos:     Active apt sources in file: /etc/apt/sources.list.d/google-chrome.list
           deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
           Active apt sources in file: /etc/apt/sources.list.d/official-package-repositories.list
           deb http://packages.linuxmint.com sylvia main upstream import backport
           deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse
           deb http://archive.ubuntu.com/ubuntu xenial-updates main restricted universe multiverse
           deb http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse
           deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse
           deb http://archive.canonical.com/ubuntu/ xenial partner
           Active apt sources in file: /etc/apt/sources.list.d/sublime-text.list
           deb https://download.sublimetext.com/ apt/stable/
Info:      Processes: 197 Uptime: 1:06 Memory: 2106.2/3879.7MB
           Init: systemd v: 229 runlevel: 5 default: 2 Gcc sys: 7.3.0 alt: 5
           Client: Shell (bash 4.3.481 running in gnome-terminal-) inxi: 2.2.35
```

**Comment by JosephMcc** [comment] 2018-04-09 21:48
Typically we close any bug reports that don't use the provided issue template. It's there for a reason. I'm not going to close this one since you provided excellent info but please use it in the future.

**Comment by aerkiaga** [comment] 2018-04-09 23:28
Sorry, I didn't inform myself appropriately before noticing the issue. Next
time I'll use the template.

On Apr 9, 2018 23:48, "JosephMcc" <notifications@github.com> wrote:

Typically we close any bug reports that don't use the provided issue
template. It's there for a reason. I'm not going to close this one since
you provided excellent info but please use it in the future.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/linuxmint/linuxmint/issues/9#issuecomment-379904612>,
or mute the thread

**Comment by xenopeek** [comment] 2018-06-04 09:35
I'm unable to reproduce this on Linux Mint 19 pre-beta. If you're planning to try out the Linux Mint 19 beta (should arrive today) it would be useful if you could report if you can still reproduce it. For now closing this as it appears solved in the new release.

**Closed by xenopeek** 2018-06-04 09:35 UTC
