### ISSUE TITLE
menu entries created by menulibre are shown twice

### ISSUE THREAD

**Issue by DrVanScott** [linuxmint/linuxmint#151] opened 2019-09-14 08:51 UTC
Hi,
i am using Linux Mint 19.2 Tina with the MATE desktop.

Whenever i create a new starter using the "menulibre" application, it is shown twice in the menu afterwards.
Menulibre creates a .desktop file in $HOME/.local/share/applications with the following content:

    [Desktop Entry]
    Version=1.1
    Type=Application
    Name=ttt
    Comment=Eine Kurzbeschreibung dieser Anwendung
    Icon=applications-other
    Exec=test
    Actions=
    Categories=Development;

The file is stored with filename "menulibre-ttt.desktop"

As soon as i rename the file to e.g. "menulibr-ttt.desktop" (e removed), the entry is only shown once in the menue. So i assume the filename prefix "menulibre-" is somehow significant for the menu

**Comment by paul59** [comment] 2019-11-25 11:11
I have a similar (related?) issue. I've added a couple of launchers to the Sound & Vision category but then find the entire category is duplicated after reloading plug-ins. Tried hiding/unhiding to no avail.

Following the advice on this thread:

https://forums.linuxmint.com/viewtopic.php?f=206&t=300099

The duplicate category disappears but my launchers are moved to the 'Other' category.

Not sure if this is related but after opening and closing the menu, clicking on a taskbar button for an open program has no effect. For example, I have hexchat and firefox open and firefox has the focus. I open the menu then close it. I click on the hexchat button repeatedly and nothing happens.

**Comment by xenopeek** [comment] 2020-01-08 18:39
This can be reproduced on Linux Mint 19.3 MATE by installing and using menulibre to add a menu item. It's not reproducible with the default main menu editor (mozo).

What happens in short:

1. menulibre and mozo both add a line like `<Filename>_filename_.desktop</Filename>` for a new menu item to the file `~/.config/menus/applications-merged`;
2. menulibre also creates a file for the category as `~/.config/menus/applications-merged/user-_category_.menu` and puts the same line for the new menu item in that.

The problem is that second file. If you remove the `~/.config/menus/applications-merged/user-*.menu` files and reload plugins on the menu, the duplicate categories and menu items go away. The menu items didn't move to another category for me.

I think this is a menulibre issue hence it's been replaced by mozo. As such, closing this issue as I don't see an action for mintmenu.

**Closed by xenopeek** 2020-01-08 18:39 UTC
