### ISSUE TITLE
Tara mint 19, avahi/mdns doesn't work

### ISSUE THREAD

**Issue by paul-at-k** [linuxmint/linuxmint#87] opened 2018-09-14 00:39 UTC
**Behavior:**
`paulc@eleazer:~$ ping Heathers-MacBook-Pro.local
ping: Heathers-MacBook-Pro.local: Name or service not known`

**Desired behaviour:**

`paulc@eleazer:~$ ping Heathers-MacBook-Pro.local

PING Heathers-MacBook-Pro.local(Heathers-MacBook-Pro.local (fe80::845e:5fff:feeb:914d%br0)) 56 data bytes
64 bytes from Heathers-MacBook-Pro.local (fe80::845e:5fff:feeb:914d%br0): icmp_seq=1 ttl=64 time=0.094 ms
64 bytes from Heathers-MacBook-Pro.local (fe80::845e:5fff:feeb:914d%br0): icmp_seq=2 ttl=64 time=0.099 ms
64 bytes from Heathers-MacBook-Pro.local (fe80::845e:5fff:feeb:914d%br0): icmp_seq=3 ttl=64 time=0.090 ms
64 bytes from Heathers-MacBook-Pro.local (fe80::845e:5fff:feeb:914d%br0): icmp_seq=4 ttl=64 time=0.090 ms`

**Packet Trace:**

![avahi_trace](https://user-images.githubusercontent.com/43255619/45522793-a3134b80-b808-11e8-813d-19f0abbdbabe.png)

**Interface setup:**
`root@eleazer:/home/paulc# ifconfig
br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.1.2  netmask 255.255.255.0  broadcast 10.0.1.255
        inet6 fe80::845e:5fff:feeb:914d  prefixlen 64  scopeid 0x20<link>
        ether 86:5e:5f:eb:91:4d  txqueuelen 1000  (Ethernet)
        RX packets 11487  bytes 18562392 (18.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7705  bytes 1030111 (1.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 18:60:24:a2:4f:76  txqueuelen 1000  (Ethernet)
        RX packets 15701  bytes 19064138 (19.0 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7851  bytes 1075466 (1.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xce900000-ce920000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 153  bytes 16067 (16.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 153  bytes 16067 (16.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:f7:66:bd  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**Config files:**
[avahi-daemon.conf.txt](https://github.com/linuxmint/mintsystem/files/2381426/avahi-daemon.conf.txt)
[nsswitch.conf.txt](https://github.com/linuxmint/mintsystem/files/2381427/nsswitch.conf.txt)
[resolved.conf.txt](https://github.com/linuxmint/mintsystem/files/2381428/resolved.conf.txt)

**Avahi Debug:**
[avahi_console.txt](https://github.com/linuxmint/mintsystem/files/2381433/avahi_console.txt)

**Comment by xenopeek** [comment] 2020-01-08 15:39
I hope you did get this to work. Closing it here considering its age and that on the support forums I see Linux Mint 19.3 users making use of Avahi/mDNS. What was the root cause of your issue I can't say; maybe something was fixed since or something else was the matter.

**Closed by xenopeek** 2020-01-08 15:39 UTC
