### ISSUE TITLE
Ubiquity : keyboard is modified during LM installation

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#311] opened 2020-10-09 22:28 UTC
I installed LM 20 Cinnamon, choosing French language and keyboard "Français (azerty)" or "Français".
At the screen asking to choose a computer and a user names, the keyboard is still QWERTY instead of AZERTY (q instead of a...).

![Capture d’écran du 2020-09-25 08-55-18](https://user-images.githubusercontent.com/3955499/95636441-74233e80-0a8f-11eb-8f15-e05eb8ded6f6.png)

**Comment by SimonIremonger** [comment] 2020-10-17 19:40
Maybe, the keyboard-layout is not actually changing -- maybe it stays in whatever setting (qwerty default) it is in, until you boot into installed system?

**Comment by InfoLibre** [comment] 2020-10-17 19:44
In installed system, after reboot, the keyboard layout is which I chose at the beginning of the installation (Français-Azerty). But at the screen asking to choose a computer and a user names, the keyboard is still QWERTY instead of AZERTY (q instead of a...).

**Comment by InfoLibre** [comment] 2020-10-17 20:10
During the installation, these messages appear :

![Capture d’écran du 2020-10-17 22-07-36](https://user-images.githubusercontent.com/3955499/96352692-7f94ec00-10c5-11eb-91a0-a81f7702bcde.png)

![Capture d’écran du 2020-10-17 22-08-41](https://user-images.githubusercontent.com/3955499/96352696-83287300-10c5-11eb-9e7d-42ee36c4d28e.png)

**Comment by clefebvre** [comment] 2020-12-18 16:24
I can't reproduce this issue.

I select French - French, the keyboard is AZERTY when I test it in the test entry box... then I continue the installation and get to the User Info page and it's still AZERTY.

**Comment by clefebvre** [comment] 2020-12-18 16:27
It reminds me of an issue which was fixed in Slick Greeter:

https://github.com/linuxmint/slick-greeter/commit/b12098dc07873b965be9497a00cd5d1a6ed05380

Do you use a wireless Logitech keyboard by any chance? I have one here, I'll test as well.

**Comment by InfoLibre** [comment] 2020-12-18 16:43
No, it's a Genius keyboard. I did not have this bug with LM 19 and this keyboard. But it's in a VirtualBox VM.

**Comment by InfoLibre** [comment] 2020-12-18 16:45
I'm making a video...

**Comment by InfoLibre** [comment] 2020-12-18 17:08
The video is here : https://infolib.re/lm/

**Comment by clefebvre** [comment] 2020-12-29 13:45
Thanks for the video @InfoLibre.. 

I can't reproduce this issue here. I tested again with a French wireless Logitech keyboard (that's the only French keyboard I have..). Azerty sticks.. there's no problem for me.

**Comment by clefebvre** [comment] 2020-12-29 13:48
Ah wait.. it happened here in a VM as well.

**Comment by clefebvre** [comment] 2020-12-29 13:52
OK, it happens just after we the codecs page. That's when ubiquity calls ubuntu-drivers and installs the OSS drivers.

**Comment by clefebvre** [comment] 2020-12-29 13:53
It looks like it only happens with some layouts but not others.

**Comment by clefebvre** [comment] 2020-12-29 13:59
I can reproduce it in Vbox with French - French, French - Obsolete variante, French - azerty. It happens just after the codecs page, when ubiquity calls ubuntu-drivers to install the OSS drivers (that's when we see the resolution change temporarily).

**Comment by clefebvre** [comment] 2020-12-29 14:00
It's not happening in real HW... it might have to do with the drivers installed.

**Comment by clefebvre** [comment] 2020-12-29 14:04
OK, confirmed.

- Use ubiquity to choose the French keyboard
- Open a terminal and run `sudo ubuntu-drivers --free-only install`
- Keyboard switches to Qwerty

**Comment by clefebvre** [comment] 2020-12-29 14:09
The package `open-vm-tools` does that.

**Comment by clefebvre** [comment] 2020-12-29 14:17
In `open-vm-tool`'s `postinst` there's a call to `udevadm trigger`, that resets the keyboard layout and the display resolution.

**Comment by clefebvre** [comment] 2020-12-29 17:18
I can't reproduce the issue upstream. There are differences in the way we handle keyboard layouts and also in the way we call ubuntu-drivers from ubiquity. For some reason it's not happening upstream so I won't report it there.

**Comment by clefebvre** [comment] 2020-12-29 17:50
Fixed.

**Closed by clefebvre** 2020-12-29 17:50 UTC

**Comment by InfoLibre** [comment] 2021-01-07 07:26
Tested in LM 20.1 (not edge), it works.
