### ISSUE TITLE
STOP! Clem! Your rel URL change ruins mint-release-upgrade's links! Why do you have to simplify everything THIS way?

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/linuxmint#633] opened 2024-01-06 19:44 UTC
As you can clearly see:
![Screenshot showing two windows with the content of /etc/linuxmint/info in Victoria and in a Virginia VM](https://github.com/linuxmint/linuxmint/assets/118076740/05e08199-250c-48d0-a571-34618555db8b)
You've deprecated the rel_EDITION_CODENAME[_whatsnew].php URLs and only want those without CODENAME anymore? Well, then you've to upgrade the links in mint-release-upgrade. But only for the 21.X since old releases still have the old URL form (which should stay the current form! revert the change please!) BUT what for users who are using 20.X AND THE DAILY BUILDS PPA? Stop it, please, please let's have three again and please update that in mint-info too if I can convince you to revert this change. I had already noticed that you only posted one blog post for the last beta release - and only one screenshot! :( But it was yesterday that I noticed that the release notes url doesn't contain the codename and today I checked and saw this in /etc/linuxmint/info too - please stop it. Please don't create that chaos and broken links. And if you really want to do, at least let rel_virginia_cinnamon.php (and mate and xfce) all point to the page which is now for all.
Thanks. Please forgive me for the intrusive comment. The heading has to be the way that you hopefully see it before the stable release as the beta is closed now but I may try other contact ways like email too.

**Comment by clefebvre** [comment] 2024-01-12 17:38
This is by design and fixed in mintupdate.

**Closed as completed by clefebvre** 2024-01-12 17:38 UTC

**Comment by Jeremy7701** [comment] 2024-01-12 17:49
I got a mintgrade update for Mint 21.2 today
But after the install,
```
apt-cache show mintupgrade
Package: mintupgrade
Version: 2022.08.13
```
Is this correct?
Note that LMDE6 has a much more correct looking
```
apt-cache show mintupgrade
Package: mintupgrade
Version: 2023.10.24
```

**Comment by nd3w** [comment] 2024-01-13 13:15
> I got a mintgrade update for Mint 21.2 today But after the install,
> 
> ```
> apt-cache show mintupgrade
> Package: mintupgrade
> Version: 2022.08.13
> ```
> 
> Is this correct? Note that LMDE6 has a much more correct looking
> 
> ```
> apt-cache show mintupgrade
> Package: mintupgrade
> Version: 2023.10.24
> ```

Mine's (yesterday's update):

Package: mintupgrade
Version: 2024.01.12

**Comment by Jeremy7701** [comment] 2024-01-13 20:03
Me too!
