### ISSUE TITLE
System does not respond for system events

### ISSUE THREAD

**Issue by KES777** [linuxmint/linuxmint#114] opened 2019-03-13 11:56 UTC
When I upgrade from 18.3 to 19.1 and use mouse to select text.

Next situation may occur:
I release the left mouse button, but OS still thinks that it is still holded.
when I try to select text again then current selection disappear and I can not do notthing with mouse:
switch to different window, open menus. Just right click work.
Keyboard works fine, I can switch to another window, use hotkeys etc.

When this situation occur I can only reboot system to continue my work

How to reproduce:
try to select something and release left mouse button in a way that selection process still continue.
probably try to press right/middle mouse button or so

**Comment by KES777** [comment] 2019-03-14 12:29
sharp steps to reproduce:

1. Run LibreOffice
2. Start to select cells
3. while selecting move cursor out of window
4. release LMB (left mouse button)
5. try to click on other window or select different cell. You will see that click events are not handled anymore

**Comment by xenopeek** [comment] 2020-01-08 15:59
I hope you managed to solve this issue. Tried to reproduce it on Linux Mint 19.3 Cinnamon with your steps but the issue doesn't happen here. Closing this here also considering its age. If you still have this issue you can reopen this issue. Please then add your current Linux Mint version and desktop environment.

**Closed by xenopeek** 2020-01-08 15:59 UTC

**Comment by KES777** [comment] 2020-01-08 17:18
It seems this occur because of broken hardware. My mouse eventually reinitializes. Just like I press LMB, take the cord from USB, then plug mouse back into USB but with released buttons.

But OS still thinks that mouse button still pressed. This is reproducible only on that mouse and only when `(EMI?) reinitilizing` event occur

Sorry, I do not remember sharp message and can not reproduce, because mouse was changed by guarantee

**Comment by xenopeek** [comment] 2020-01-08 17:21
Sorry you had to replace the mouse but happy you managed to find the cause.

**Comment by KES777** [comment] 2020-01-09 10:57
Probably system does not flush mouse state in some cases.
