### ISSUE TITLE
Please stop patching Firefox's home page

### ISSUE THREAD

**Issue by thetoastcaper** [linuxmint/linuxmint#138] opened 2019-06-23 21:04 UTC
Replacing Firefox's homepage with a very outdated-looking start page is a pretty unfriendly thing to start off your new users with, and just changing it to its proper page is the subject of a handful of community posts. There is also the issue of the Linux Mint start page being mislabeled as "Firefox Home" in the homepage settings.

It would really be better to keep the homepage untouched, please.

**Comment by dashohoxha** [comment] 2019-06-24 07:15
I think they should make Google the default search on Firefox, instead of Yahoo. Having Yahoo as the default search is quite unfriendly.

**Comment by zcot** [comment] 2019-07-27 17:18
@thetoastcaper I don't see the comment very much since it can be easily configured as per user. On the forum, or IRC, or other articles, I just haven't see the complaint. -maybe only a few times in the last number of years. I haven't really seen that it is any issue.

Anyway, make `about:newtab` the homepage and it will act exactly like the Firefox default from Mozilla which is what they do, but this Firefox is the Firefox from Mint so its default _is_ in fact the LinuxMint page which seems to make a sort of sense.

@dashohoxha note that many users who have the most interest in privacy, which is often common in open source and security circles do not use Google. Although Startpage is available as a private mask to Google. Anyway, there's this: https://www.linuxmint.com/searchengines.php

**Comment by dashohoxha** [comment] 2019-07-27 19:18
@zcot I actually use chrome, to be honest. But whenever I open Firefox, I have to type google.com before I start a search. I believe that this is the case with many users, but I may be wrong. I don't know if there are any usage stats about this. In case that most of the users do the same, than it is not user friendly.

I believe that LinuxMint users are worthy too, not only the sponsors. If some day users abandon LinuxMint for a better option/distro, then LinuxMint would become worthless and its sponsors would stop sponsoring it as well. I believe that LinuxMint is popular because it pays much attention to the users.

**Comment by zcot** [comment] 2019-07-27 20:10
@dashohoxha absolutely the users are the worth. otherwise Clem and the dev team would only be doing it for themselves I guess?

Anyway, they have provided us the means to be able to do it. I did show the previous link to show how. Or just click on the toolbar search box magnifier glass to change the settings in that manner, either work out as the same result.

And so we can easily set Google to the default search engine if that's what we want, and even just type in the toolbar search box and it will use Google (or whatever search engine we choose).

So, it's all a good thing.

**Comment by altimumdelta** [comment] 2019-07-29 18:29
Bah, I'm in favor of a linux mint specific page that would use startpage underneath.

**Comment by lytithwyn** [comment] 2019-08-02 12:29
I'm with thetoastcaper.  I just spent several minutes searching to figure out where to request this very thing, only to find (as I suspected I would) someone else has already requested it.  I love Linuxmint and I really appreciate everything Clem and the team do for us, but it really feels like the Firefox homepage is being hijacked.  My biggest problem with this is that I really like the builtin Firefox homepage, and with the Linuxmint override in distribution.ini I can't figure out a way to manually set that specific page as the homepage.  If it is desirable that the user see the LinuxMint page first thing, It would be much better to preset a custom URL as the homepage in the preferences screen, so that if a person chooses "Firefox Home Page", it does in fact go to that page.

Again, thanks for everything Clem and the Linuxmint Team!

**Comment by xenopeek** [comment] 2020-01-08 17:01
Looking at how it is set up on Linux Mint 19.3 (may also have been changed in Firefox for earlier releases):

- in Home settings the default homepage is a Custom URL
- changing the homepage there to Firefox Home does change it to the default Firefox homepage
- the default search engine can easily be switched from Yahoo to Startpage (anonymous Google) or DuckDuckGo in Search settings
- to add Google as a search engine requires a step more by clicking on the "Find more search engines" link at the bottom of Search settings.

That looks to match this feature request so I'm closing it.

**Closed by xenopeek** 2020-01-08 17:01 UTC

**Comment by lytithwyn** [comment] 2020-01-08 17:28
Yes, I can confirm this is the behavior I currently see in 19.2.  I just noticed it the other day, though I'm not sure when the change happened.  Thanks so much!
