### ISSUE TITLE
Feature request : updating Memtest86+

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#358] opened 2021-02-09 16:28 UTC
Updating Memtest86+ in the GRUB menu : https://www.memtest.org/#downiso
Memtest86+ V5.31b (12/04/2020)

**Comment by SimonIremonger** [comment] 2021-03-11 20:02
Upstream is quite clear:-
Here is all the latest change logs for memtest86+ this is not ready for production.:

    *** Enhancements in v5.31b : ***
    After a long hiatus without updates and following numerous requests, I've started compiling many codes branches to release public builds again! Here is Memtest86+ 5.31b, with many bug fixes in the core functions. **This build is not ready for production yet, because it lacks some feedbacks from beta-testers.** Additional features and updated detection code will follow soon, as soon I have access to my lab with all the reference test platforms. It's currently inaccessible due to the COVID19 lockdown.
    If you find a bug or regression in this build, please send your feedback to memtest (-A-) memtest.org. Thank you!

I note, for newer machines, commercial-but-free-of-charge memtest86.com UEFI memtest seems more 'useful in practice'... Linuxmint only provides memtest86+ for legacy-booting...

**Comment by SimonIremonger** [comment] 2021-03-11 20:03
@InfoLibre bearing in mind the above, please consider closing this bug/issue for now.

**Closed** 2021-03-12 16:09 UTC
