### ISSUE TITLE
Games have a bar on the bottom and right sides of my desktop in full-screen mode.

### ISSUE THREAD

**Issue by sheast21** [linuxmint/linuxmint#199] opened 2019-08-04 00:03 UTC
Games have a bar on the bottom and right sides of my desktop in full-screen mode, this seems effect some games like cs:go and gta 5 but not others. I know this is a  linux mint bug because it doesn't happen on any other distro and didn't use to happen on Linux mint. It seems to fix 
cursor issues that i had on other distros when changing volume.
![gta5](https://user-images.githubusercontent.com/53667480/62417863-95c9a000-b618-11e9-97d9-6eaa92659986.png)
![csgoloading](https://user-images.githubusercontent.com/53667480/62417870-c7426b80-b618-11e9-9bee-c85ad92e558f.png)

**Comment by mtwebster** [comment] 2020-01-08 11:40
What desktop? (cinnamon, xfce or mate)

What version of the desktop?
Looks like a duplicate of this: https://github.com/linuxmint/muffin/issues/530?

this should be fixed in muffin 4.4.2 (assuming your desktop is cinnamon)

**Comment by xenopeek** [comment] 2020-01-08 11:41
@mtwebster this is an older issue, I moved it here from mintsystem as it's unrelated to that.

And indeed, on Linux Mint 19.3 this issue is fixed. Closing.

**Closed by xenopeek** 2020-01-08 11:41 UTC
